blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# @Time    : 2018/12/2 7:49 PM
# @Author  : LiJinzhou
# @File    : urls.py


from django.conf.urls import url
import views


urlpatterns = [
    url(r'^list/$', views.index),
    url(r'^article/(?P<article_id>\d+)$', views.article_page, name="article_page"),
    url(r'^edit/(?P<article_id>\d+)$', views.edit_page, name="edit_page"),
    url(r'^edit/action/$', views.edit_action, name="edit_action"),
]

myblog/urls.py
# coding: utf-8
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # 后台管理系统url
    url(r'^admin/', admin.site.urls),

    # blog app根url
    url(r'^blog/', include(("blog.urls", "blog"), namespace="blog")),
]

blog/models.py
# coding: utf-8


from __future__ import unicode_literals

from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=20, verbose_name="标题")
    content = models.TextField(verbose_name="内容", null=True, blank=True)

    def __unicode__(self):
        return self.title

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from blog.models import Article


def index(request):
    articles = Article.objects.all()
    return render(request, "index.html", {"articles": articles})


def article_page(request, article_id):
    article = Article.objects.get(id=article_id)
    return render(request, "article-detail.html", {"article": article})


def edit_page(request, article_id):
    if int(article_id) > 0:
        article = Article.objects.get(id=article_id)
        return render(request, 'article-edit.html', {"article": article})
    return render(request, 'article-edit.html')


def edit_action(request):
    title = request.POST.get("title", "")
    content = request.POST.get("content", "")
    id = int(request.POST.get("id"))
    if id == 0:
        if title != "" and content != "":
            Article.objects.create(title=title, content=content)
        return index(request)

    article = Article.objects.get(id=id)
    article.title = title
    article.content = content
    article.save()
    articles = Article.objects.all()
    return render(request, 'index.html', {"articles": articles})

blog/templates/article-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章详情</title>
    <style>
        *{
            box-sizing: border-box;
        }
        a:link,a,a:visited{
            color: #58585b;
            text-decoration: none;
        }
        a:hover{
            color: #0066cc;
            text-decoration: underline;
        }
        p{
            color: #58585b;
            font-size: 14px;
            line-height: 1.6rem;
        }
        h1{
            font-size: 26px;
            font-weight: normal;
        }
        .article-container{
            position: relative;
            margin:30px auto;
            width: 100%;
            max-width:1000px;
            border:1px solid #efefef;
            padding: 30px;
        }
        .article-header{
            height: 50px;
            line-height: 50px;
        }
        .article-content{
            position: relative;
        }
        .article-list{
            padding: 0;
            list-style: none;

        }
        .article-list li{
            width: 100%;
            line-height: 40px;
            margin-bottom: 10px;
            border: 1px solid #f5f5f5;
            padding-left: 10px;
        }

    </style>
</head>
<body>
<div class="article-container">
    <div class="article-header">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="article-content">

        <p>{{ article.content }}</p>

        <p><a href="{% url 'blog:edit_page' article.id %}">编辑文章 »</a></p>
    </div>
</div>
</body>
</html>

blog/templates/article-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章详情</title>
    <style>
        *{
            box-sizing: border-box;
        }
        a:link,a,a:visited{
            color: #58585b;
            text-decoration: none;
        }
        a:hover{
            color: #0066cc;
            text-decoration: underline;
        }
        p{
            color: #58585b;
            font-size: 14px;
            line-height: 1.6rem;
        }
        h1{
            font-size: 26px;
            font-weight: normal;
        }
        .article-container{
            position: relative;
            margin:30px auto;
            width: 100%;
            max-width:1000px;
            border:1px solid #efefef;
            padding: 30px;
        }
        .article-header{
            height: 50px;
            line-height: 50px;
        }
        .article-content{
            position: relative;
        }
        .article-list{
            padding: 0;
            list-style: none;

        }
        .article-list li{
            width: 100%;
            line-height: 40px;
            margin-bottom: 10px;
            border: 1px solid #f5f5f5;
            padding-left: 10px;
        }
        .edit-col{
            width:100%;
            position: relative;
            margin-bottom: 10px;
        }
        .edit-col label{
            width: 100%;
            display: block;
            line-height: 30px;
        }
        .edit-text{
            width: 100%;
            max-width: 100%;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px;
            border:1px solid #efefef;
            line-height: 20px;
            font-size: 14px;
        }
        .align-center{
            text-align: center;
        }
        .edit-col button{
            padding: 8px 20px;
            color: #ffffff;
            background: #ff9800;
            border:none;
            outline: none;
            font-size: 16px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px;
            cursor: pointer;
        }
        .edit-col button:hover{
            background: #ff8000;
        }
    </style>
</head>
<body>
<div class="article-container">
    <form action="{% url 'blog:edit_action' %}" method="POST">
        <div class="edit-col">
            <label for="">文章标题</label>
            <input name="title" value="{{ article.title }}" type="text" class="edit-text">
        </div>
        <div class="edit-col">
            <label for="">文章内容</label>
            <textarea name="content" id="" class="edit-text">{{ article.content }}</textarea>
        </div>
        <input hidden name="id" value="{{ article.id|default:'0' }}" type="text" class="edit-text">
        {% csrf_token %}
        <div class="edit-col align-center"><button>提交</button></div>
    </form>

</div>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'blog:edit_page' 0 %}">写新文章</a><br/><br/>
    {% for article in articles %}
        <a href="{% url 'blog:article_page'  article.id %}">{{  article.title }}</a>
        <br/>
    {% endfor %}
</body>
</html>